apiVersion: v1
kind: Service
metadata:
  name: frontend-service 
  labels:
    app: frontend
    tier: web
spec:
  selector:
    app: frontend
  type: ClusterIP  
  
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 80