apiVersion: v1
kind: Service
metadata:
  name: mysql-service # Must match serviceName in the StatefulSet
  labels:
    app: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
  clusterIP: None # Makes the Service Headless (provides DNS records for individual Pods)